# Generated by Django 5.2.17 on 2026-09-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiza', '0003_categoria_tarefa_data_conclusao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='icone',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Data Limite'),
        ),
        migrations.DeleteModel(
            name='Subtarefa',
        ),
    ]
